
project_id = "evghwzipbhnwhwkshumt"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true

[storage]
enabled = true

[functions]
[functions.initiate-stk-push]
verify_jwt = false

[functions.stk-callback]
verify_jwt = false
