// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evghwzipbhnwhwkshumt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2Z2h3emlwYmhud2h3a3NodW10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NTI4NzQsImV4cCI6MjA1NjEyODg3NH0.J4vA31adP_RaOy-3K2yQzI2V31-DrzPN4StfFQgSXyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);